# Generated by Django 3.0 on 2020-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Good'), ('5', 'Excellent')]),
        ),
    ]
